import re
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    print('strona logowania otwarta')
    page.get_by_role('textbox', name='username').click()
    page.get_by_role('textbox', name='username').clear()
    page.get_by_role('textbox', name='username').fill('Admin')
    print('login wpisany')
    page.get_by_role('textbox', name='password').click()
    page.get_by_role('textbox', name='password').clear()
    page.get_by_role('textbox', name='password').fill('admin123')
    print('haslo wpisane')
    page.get_by_role('button', name='Login').click()
    print('button klikniety')
    page.wait_for_url('https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index')
    print('user zalogowany')
    # adding employee
    page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee')
    page.wait_for_url('https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee')
    print('formularz nowego pracownika otwarty')
    page.get_by_placeholder('First Name').click()
    page.get_by_placeholder('First Name').clear()
    page.get_by_placeholder('First Name').fill('Jan')
    print('imie wpisane')
    page.get_by_placeholder('Middle Name').click()
    page.get_by_placeholder('Middle Name').clear()
    page.get_by_placeholder('Middle Name').fill('Piotr')
    print('drugie imie wpisane')
    page.get_by_placeholder('Last Name').click()
    page.get_by_placeholder('Last Name').clear()
    page.get_by_placeholder('Last Name').fill('Nowak')
    print('nazwisko wpisane')
    page.locator('form').get_by_role('textbox').nth(4).dblclick()
    page.locator('form').get_by_role('textbox').nth(4).fill('861105')
    print('ID wpisane')
    page.get_by_role('button', name='Save').click()
    print('pracownik utworzony')
    expect(page.get_by_placeholder('First Name')).to_be_visible()
    expect(page.get_by_placeholder('First Name')).to_have_value('Jan')
    print('imie sprawdzone')
    expect(page.get_by_placeholder('Middle Name')).to_be_visible()
    expect(page.get_by_placeholder('Middle Name')).to_have_value('Piotr')
    print('drugie imie sprawdzone')
    expect(page.get_by_placeholder('Last Name')).to_be_visible()
    expect(page.get_by_placeholder('Last Name')).to_have_value('Nowak')
    print('nazwisko sprawdzone')
    expect(page.locator('div').filter(has_text=re.compile(r'^Employee IdOther Id$')).get_by_role(
        'textbox').first).to_be_visible()
    expect(page.locator('div').filter(has_text=re.compile(r'^Employee IdOther Id$')).get_by_role(
        'textbox').first).to_have_value('861105')
    print('ID sprawdzone')
    expect(page.locator('#app')).to_contain_text('Jan Nowak')
    print('imie i nazwisko pasuja')
    # searching for a user
    page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList')
    page.wait_for_url('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList')  # Precondition 1
    print('strona zaladowana')
    page.get_by_role('textbox').nth(2).click()
    page.get_by_role('textbox').nth(2).clear()
    page.get_by_role('textbox').nth(2).fill('861105')  # Step 1
    print('ID wpisane')
    page.get_by_role('button', name='Search').click()  # Step 2
    print('button klikniety')
    expect(page.locator('div').filter(has_text=re.compile(r'^\(1\) Record Found$')).nth(1))  # Assertion 1
    print('jest 1 wynik')
